import net.darkhax.curseforgegradle.TaskPublishCurseForge
plugins {
    id 'fabric-loom' version '1.10.+'
    id 'com.modrinth.minotaur' version "2.+"
    id 'net.darkhax.curseforgegradle' version '1.1.18'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.name
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "project.mod_id" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

repositories {
    mavenLocal()
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modCompileOnly "mezz.jei:jei-${project.minecraft_version}-fabric-api:${project.jei_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand  "mod_id": project.mod_id,
        "version": project.version,
        "minecraft_version": project.minecraft_version,
        "loader_version": project.loader_version
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "${mod_id}"
    uploadFile = jar
    versionName = "${minecraft_version}-${mod_version}"
    versionNumber = "${mod_version}"
    versionType = "${releaseType}"
    gameVersions = ["${minecraft_version}"] as Iterable<? extends String>
    loaders = ["fabric"]
    changelog = rootProject.file("changelog.md").text
}

tasks.register('curseforge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    def mainFile = upload(curseforge_id, jar)
    mainFile.changelog = rootProject.file('changelog.md').text
    mainFile.addGameVersion(minecraft_version)
    mainFile.releaseType = "${releaseType}"
    mainFile.displayName = "${minecraft_version}-${mod_version}"
    mainFile.addModLoader("Fabric")
}

def targetJavaVersion = 17
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}