# Fabric Properties
minecraft_version=1.21.1
loader_version=0.19.3
loom_version=1.15-SNAPSHOT
# Mod Properties
mod_id=hemomancy
mod_version=1.21.1-1.3.1-fabric
maven_group=ru.easynull
mod_subtitle=1.3.1 - Update loader
# Dependencies
fabric_version=0.116.12+1.21.1
emi_version=1.2.6+1.21.1
# Publish
releaseType=beta
curseforge_id=1340370
# Gradle
org.gradle.jvmargs=-Xmx1G
