name: Release Mod

on:
  workflow_dispatch:
  push:
    branches: [ "1.21.4-neo" ]

permissions:
  contents: write

jobs:
  release:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version info
        id: versions
        run: |
          MOD_VERSION=$(grep -oP 'mod_version\s*=\s*\K.+' gradle.properties)
          MC_VERSION=$(grep -oP 'minecraft_version\s*=\s*\K.+' gradle.properties)
          VERSION=$MOD_VERSION
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
          echo "MC_VERSION=$MC_VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Collect artifacts
        run: |
          # Поиск JAR файлов
          echo "JAR files found:"
          find . -name "*.jar" -type f
          
          # NeoForge JAR
          NEO_JAR=$(find neoforge/build/libs -name "*.jar" -type f | head -1)
          echo "NEO_JAR=$NEO_JAR" >> $GITHUB_ENV
          echo "NeoForge JAR: $NEO_JAR"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: |
            ### Minecraft ${{ env.MC_VERSION }}
            Built for NeoForge
          files: ${{ env.NEO_JAR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}