name: Release Mod

on:
  workflow_dispatch:
  push:
    branches: [ "1.21.4-neo" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version info
        id: versions
        run: |
          MOD_VERSION=$(grep -oP 'mod_version\s*=\s*\K.+' gradle.properties)
          MC_VERSION=$(grep -oP 'minecraft_version\s*=\s*\K.+' gradle.properties)
          VERSION=$MOD_VERSION
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
          echo "MC_VERSION=$MC_VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT
          echo "minecraft_version=$MC_VERSION" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build all modules
        run: ./gradlew build

      - name: Collect artifacts
        id: collect-jars
        run: |
          # NeoForge JAR
          NEO_JAR=$(ls neoforge/build/libs/*-${MOD_VERSION}.jar | head -1)
          echo "NEO_JAR=$NEO_JAR" >> $GITHUB_ENV
          
          # Список всех JAR для релиза
          echo "ARTIFACTS=${NEO_JAR}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: |
            ### Minecraft ${{ env.MC_VERSION }}
          files: |
            ${{ env.NEO_JAR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}